### PR TITLE
Add data folder branch

### PR DESCRIPTION
**Pull request by mcpat1993**
Hopefully this will be changing the file hierarchy to have a data folder now instead of a test data folder.

### CODE REVIEW

**Comment by EthanWelsh** [comment]
Could you remove those .DS_Stores?

https://help.github.com/articles/ignoring-files/

**Comment by mcpat1993** [comment]
Yo I assume that I'm not capable of causing any harm to the repo at this point. Please please please tell me if you tell me to do something in git and I either don't do it or do it wrong. I think I got them removed. could you let me know if I need a gitignore in every single folder? Those files were put in automatically, not sure why.

**Comment by alexlafroscia** [comment]
If you're changing the path to the `test_data` directory, please update the tests that depend on those files :smile:

**Comment by mcpat1993** [comment]
Was that path in test_yelp_data.py the only place the path was used? It should be fixed now.

**Comment by alexlafroscia** [comment]
Yeah, that should do it.

**Pull request closed without merging**
