### PR TITLE
Add sentiment analysis feature

### PR DESCRIPTION
**Pull request by alexlafroscia**
Adds a function that will return a positive or negative float based on the sentiment of the text passed to it.

### CODE REVIEW

**Comment by alexlafroscia** [comment]
I was thinking that another good feature might be "sentiment intensity", which I think NLTK might also provide.  Thoughts?

**Comment by mcpat1993** [comment]
Isn't this what you already were kind of going for? On Facebook you referred to a negative and positive decimal value which to me already implies a representation of intensity or not? Can you elaborate on this?

**Comment by alexlafroscia** [comment]
Yeah, I guess you're right.  I just know that NLTK is able to extract intensity through things like "all caps" words, exclamation points, etc.  But you're right, that's probably already factored into how positive or how negative the review is.

**Comment by alexlafroscia** [comment]
I added the Travis config to this PR, since this is where we add the tests and dependencies.  I tested it in my fork, and it all works; as long as Travis is turned on for this repo as well, it should run automatically after it gets pulled.  I tried to get Travis to see this PR but I don't think it can, since it was created before Travis was turned on.

As an example of what this looks like, you can see the fork's test run [here](https://travis-ci.org/alexlafroscia/Yulp).

**Pull request merged**
